logging:
  level:
    graphql: ERROR
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

spring:
  main:
    lazy-initialization: true

  jpa:
    generateDdl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        globally_quoted_identifiers: true
        ddl-auto: create
        use_sql_comments: true
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 123123
    username: root
    url: jdbc:mysql://localhost:3306/lms?zeroDateTimeBehavior=convertToNull&autoReconnection=true&autoReconnectForPools=true&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8
